⬆️ Update Base image to v.12.0.0
brenner-tobias/addon-cloudflared pull request #106
Opened 2022-06-08 06:47 UTC by elcajon

# Proposed Changes

Base image version updated with breaking changes included. s6-overlay was updated from v2 to latest v3.
See https://github.com/hassio-addons/addon-base/releases/tag/v12.0.0

I updated files and structures to work with latest s6 version.
The new service definition is quite more complex than the legacy /etc/cont-init.d and /etc/services.d directives. 

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2022-06-08 09:56 UTC, brenner-tobias commented
Thanks a lot for bringing that up. 
I think, we also have to update the apparmor file (see [here](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/#apparmor)), don't we? this would also be a great time to check it properly, since I had no idea when creating it, to be honest...

2022-06-08 10:00 UTC, brenner-tobias requested changes
Great, thanks. I think we should also look into the Apparmor file.

2022-06-08 10:29 UTC, elcajon commented on cloudflared/rootfs/build.sh
> -    yq=4.14.1-r2
We can separate that but we need this version anyway as the new base image also updates alpine from 3.15. to 3.16. which invalidates the old yq version.

2022-06-08 10:31 UTC, elcajon commented
> Thanks a lot for bringing that up.
> I think, we also have to update the apparmor file (see [here](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/#apparmor)), don't we? this would also be a great time to check it properly, since I had no idea when creating it, to be honest...

You are right, I hoped you can have a look at it as I have no clue about Apparmor neither. 😄

2022-06-09 20:40 UTC, elcajon commented
I just updated the apparmor file paying attention to [this example](https://developers.home-assistant.io/docs/add-ons/presentation#apparmor).
I have no clue if I missed something in this part:

```
[...]
    # Access required for service functionality
    /usr/bin/cloudflared r,
[...]
```

I guess we should merge it and test the edge version.

2022-06-11 15:12 UTC, brenner-tobias commented on cloudflared/rootfs/build.sh
> -    yq=4.14.1-r2
Ah ok, makes sense then to just leave it

2022-06-11 15:12 UTC, brenner-tobias approved these changes

2022-06-11 15:13 UTC, merged

2022-06-11 20:20 UTC, brenner-tobias commented
So I did merge it in and updated my HA at home. Now unfortunately, I cannot connect anymore and since I am not at home, I have no idea, why :-)
Is this working for you @elcajon?
I will be back home tomorrow and check, what's going on there.